substitutions:
  mqtt_topic_prefix: "oscdis/f"
  sensor_throttle: 1min
  interval: 10min
  devicename: thermo

esphome:
  name: $devicename
  # name_add_mac_suffix: true

esp32:
  board: lolin32_lite
  framework:
    type: arduino

# include shared components
packages:
  connectivity: !include common/connectivity.yaml
  mqtt: !include common/mqtt.yaml

# Enable logging
logger:

mqtt:
  client_id: $devicename

time:
  - platform: sntp
    id: esptime
    on_time:
      # Every 15 minutes trigger a BLE scan and fetch data
      - seconds: 0
        minutes: /15
        then:
          - esp32_ble_tracker.start_scan:

i2c:
   - id: bus_a
     sda: 19
     scl: 22
     scan: true

# enable BLE tracker component, required for
esp32_ble_tracker:
  scan_parameters:
    active: false
    continuous: false
    duration: 2min

# uncomment for BLE scan logs
text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"

sensor:
  - platform: htu21d
    i2c_id: bus_a
    temperature:
      name: "Room Temperature"
      id: htu_temp
      filters:
        throttle: $sensor_throttle
      state_topic: ${mqtt_topic_prefix}/temp"
    humidity:
      name: "Room Humidity"
      id: htu_hum
      filters:
        throttle: $sensor_throttle
      state_topic: ${mqtt_topic_prefix}/hum"
    update_interval: $interval
  - <<: !include { file: common/xiaomi_hhcc.yaml, vars: { id: 'A', mac_address: 'c4:7c:8d:6d:7b:ab' } }
  - <<: !include { file: common/xiaomi_hhcc.yaml, vars: { id: 'B', mac_address: 'c4:7c:8d:6c:51:6a' } }
  - <<: !include { file: common/xiaomi_hhcc.yaml, vars: { id: 'C', mac_address: 'c4:7c:8d:6d:7b:a0' } }
  - <<: !include { file: common/xiaomi_hhcc.yaml, vars: { id: 'D', mac_address: 'c4:7c:8d:6d:79:d5' } }

graph:
  - id: temp_graph
    duration: 1h
    x_grid: 15min
    y_grid: 5.0
    width: 128
    height: 48
    traces:
      - sensor: htu_temp
        line_type: SOLID
        line_thickness: 3
      - sensor: htu_hum
        line_type: DASHED
        line_thickness: 2

font:
  - file: "gfonts://Roboto"
    id: f1
    size: 12

display:
  - platform: ssd1306_i2c
    id: my_display
    model: "SSD1306 128x64"
    update_interval: 10s
    flip_x: false
    flip_y: false
    lambda: |-
      it.graph(0, 16, id(temp_graph));

      // Print time in HH:MM format
      it.strftime(60, 0, id(f1), TextAlign::TOP_CENTER, "%H:%M", id(esptime).now());

      // Print inside temperature (from homeassistant sensor)
      if (id(htu_temp).has_state()) {
        it.printf(0, 0, id(f1), TextAlign::TOP_LEFT , "%.1f°C", id(htu_temp).state);
      }

      // Print humidity
      if (id(htu_hum).has_state()) {
        it.printf(127, 0, id(f1), TextAlign::TOP_RIGHT , "%.1f %%", id(htu_hum).state);
      }
