# required vars:
#   mac_address: ble device mac address
#   id: short alphnumeric id, used in mqtt topic name
- platform: xiaomi_hhccjcy01
  mac_address: ${mac_address}
  temperature:
    name: "Flower ${id} Temperature"
    filters:
      throttle: ${sensor_throttle}
    state_topic: "${mqtt_topic_prefix}/${id}_temp"
  moisture:
    name: "Flower ${id} Moisture"
    filters:
      throttle: ${sensor_throttle}
    state_topic: "${mqtt_topic_prefix}/${id}_moist"